Review of the Execution Envirionment
- Delete submodule of GPy because it's not necessary
- but didn't delete submodule of GPyOpt because of following error

File "/Users/taguchi/BO/tmp/venv/lib/python3.9/site-packages/GPyOpt/core/evaluators/batch_local_penalization.py", line 67, in estimate_L
    minusL = res.fun[0][0]
TypeError: 'float' object is not subscriptable